name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: [self-hosted, Linux, X64]

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x Window/AndroidApp/car-api-hello-world/gradlew

    - name: Build with Gradle
      run: cd Window/AndroidApp/car-api-hello-world && ./gradlew build

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug-apk
        path: Window/AndroidApp/car-api-hello-world/app/build/outputs/apk/debug/app-debug.apk

    - name: Copy APK to local directory
      run: cp Window/AndroidApp/car-api-hello-world/app/build/outputs/apk/debug/app-debug.apk ~/apk/app-debug.apk
